rewards_engine/customer_app/urls.py
from django.urls import path
from customer_app import views

app_name='customer_app'

urlpatterns=[
    path('Create/',views.create_customer,name='create'),
    path('List/',views.list_customer,name='list'),
]

rewards_engine/rewards_engine/urls.py
from django.contrib import admin
from django.urls import path,include
from scheme_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),
    path('Schemes/',include('scheme_app.urls')),
    path('Transaction/',include('transaction_app.urls')),
    path('Customer/',include('customer_app.urls')),
]

rewards_engine/scheme_app/urls.py
from django.urls import path
from scheme_app import views

app_name='scheme_app'

urlpatterns=[
    path('List/',views.list_scheme,name='list'),
    path('Create/',views.create_scheme,name='create'),
]

rewards_engine/transaction_app/urls.py
from django.urls import path
from transaction_app import views

app_name='transaction_app'

urlpatterns=[
    path('Create/',views.create_transaction,name='create'),
    path('List/',views.list_transaction,name='list'),
]

rewards_engine/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>{% block title_block%}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static "css/master.css" %}">
    </head>
    <body>

        <nav class="navbar navbar-expand-sm navbar-dark bg-danger fixed-top">
            <a class="navbar-brand" href="#">RewardsEngine</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle {% block scheme_active %}{% endblock %}" href="#" id="schemeDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Schemes
                        </a>
                        <div class="dropdown-menu" aria-labelledby="schemeDropdown">
                            <a class="dropdown-item" href="{% url 'scheme_app:create' %}">Create</a>
                            <a class="dropdown-item" href="{% url 'scheme_app:list' %}">List</a>
                            <!-- <div class="dropdown-divider"></div> -->
                            <!-- <a class="dropdown-item" href="#">Something else here</a> -->
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle {% block customer_active %}{% endblock %}" href="#" id="customerDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Customer
                        </a>
                        <div class="dropdown-menu" aria-labelledby="customerDropdown">
                            <a class="dropdown-item" href="{% url 'customer_app:create' %}">Create</a>
                            <a class="dropdown-item" href="{% url 'customer_app:list' %}">List</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle {% block transaction_active %}{% endblock %}" href="#" id="transactionDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Transaction
                        </a>
                        <div class="dropdown-menu" aria-labelledby="transactionDropdown">
                            <a class="dropdown-item" href="{% url 'transaction_app:create' %}">Create</a>
                            <a class="dropdown-item" href="{% url 'transaction_app:list' %}">List</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>

        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>